WENI-CHANGELOG.md, package.json
- Update package details 
- Add missing changelog data
=> Chore: Update npm package details

package.json, src/components/dialog/Dialog.module.scss, src/components/dialog/Dialog.tsx, src/config/i18n/defaults.json, src/config/i18n/es/resource.json, src/config/i18n/pt-br/resource.json
=> Migrating unnnic-tab

src/index.js, src/temba/TembaSelect.module.scss, src/temba/TembaSelect.tsx, src/variables.module.scss
- Still have to migrate:
- Expressions
- Better contact search
- Clearable
- Error state
- Save a result for this flow select behavior
=> feature: unnnic select migration

src/components/dialog/Dialog.module.scss, src/components/flow/routers/case/CaseElement.module.scss, src/components/flow/routers/case/CaseElement.tsx
- Dialog width to 750px
- CaseElement layout issues
=> Fix: unnnic minor dialog issues

package.json, src/components/form/FormElement.module.scss, src/components/form/textinput/ExcellentParser.ts, src/external/index.ts, src/flowTypes.ts, src/temba/TembaSelect.module.scss, src/temba/TembaSelect.tsx, src/test/config.ts, src/utils/completion/helper.ts, yarn.lock
- Support to expressions in unnnic-select
- Support to contact search
- Added completion helper
=> feat: support to expression completion in select

package.json, src/components/flow/props.ts, src/components/flow/routers/ticket/TicketRouterForm.tsx, src/components/flow/routers/ticket/helpers.ts, src/store/flowContext.ts, src/temba/TembaSelect.tsx, yarn.lock
- Use normal select when it is not searchable, tag or a multi select component
- Better search handling
- Fixed duplicate asset creation on tag like component
- Fixed issue with Ticketer Topic selection
- Fixed issue with default contact fields selection
=> fix: unnnic select migration issues

src/components/flow/routers/random/RandomRouterForm.module.scss, src/components/form/textinput/TextInputElement.tsx
- Check if helpText exists before creating the div
- Fix random router grid layout into 2 columns
=> fix: empty help text creating an aditional grid element

src/components/flow/actions/action/Action.module.scss, src/components/flow/actions/changegroups/ChangeGroups.module.scss, src/components/flow/actions/changegroups/ChangeGroups.tsx, src/components/flow/actions/helpers.module.scss, src/components/flow/actions/helpers.tsx, src/components/flow/actions/sendbroadcast/SendBroadcast.module.scss, src/components/flow/actions/sendbroadcast/SendBroadcast.tsx, src/components/flow/actions/startflow/StartFlow.tsx, src/components/flow/actions/startsession/StartSession.module.scss, src/components/flow/actions/startsession/StartSession.tsx, src/components/flow/node/Node.module.scss, src/config/i18n/defaults.json, src/config/i18n/es/resource.json, src/config/i18n/pt-br/resource.json, src/variables.module.scss
Adjusted icons spacing and text formating in body actions
=> feat: added icons spacing and text formating in body actions

src/components/canvas/Canvas.tsx, src/components/copyAndPasteNodes.ts, src/components/flow/Flow.tsx, src/components/index.tsx, src/store/thunks.ts
Considering to mouse position on nodes pasted functionality
=> feat: pasted nodes considering to mouse position

src/components/draghelper/DragHelper.module.scss, src/components/flow/actions/action/Action.module.scss, src/components/flow/actions/sendmsg/SendMsg.module.scss, src/components/flow/actions/sendmsg/SendMsg.tsx, src/components/flow/exit/Exit.module.scss, src/components/flow/node/Node.module.scss, src/components/flow/node/Node.tsx, src/components/sticky/Sticky.module.scss, src/components/sticky/Sticky.tsx, src/components/titlebar/TitleBar.tsx, src/global.module.scss, src/variables.module.scss
Minor bugfixes from the design review
=> fix: minor bugfixes

src/components/flow/node/Node.module.scss, src/components/flow/node/Node.tsx
Added start flow message to Unnnic style
=> feat: added start flow message to unnnic style

package.json, src/components/canvas/CanvasDraggable.tsx, src/components/copyAndPasteNodes.ts, src/components/flow/actions/action/Action.module.scss, src/components/flow/actions/action/Action.tsx, src/components/flow/actions/changegroups/ChangeGroups.module.scss, src/components/flow/actions/helpers.module.scss, src/components/flow/actions/helpers.tsx, src/components/flow/actions/openticket/OpenTicket.tsx, src/components/flow/actions/sendbroadcast/SendBroadcast.module.scss, src/components/flow/actions/sendmsg/SendMsg.module.scss, src/components/flow/node/Node.module.scss, src/components/flow/node/Node.tsx, src/components/form/textinput/TextInputElement.module.scss, src/components/form/textinput/TextInputElement.tsx, src/components/index.tsx, src/components/shared.module.scss, src/components/sidebar/Sidebar.module.scss, src/components/sidebar/Sidebar.tsx, src/components/simulator/LogEvent.module.scss, src/components/simulator/Simulator.module.scss, src/components/simulator/Simulator.tsx, yarn.lock
- Simulator images and alignment
- Sidebar button style and position
- Paste uuid issues
- Textarea resize
- New node design
- Align node content
- Fix canvas height on scroll
=> Fix: Design issues

src/components/flow/actions/startsession/StartSession.module.scss, src/components/issues/IssuesTab.tsx, src/components/revisions/RevisionExplorer.tsx
- change issues and revision order
- start session alignment
=> Fix: minor fixes

src/components/flow/actions/sendemail/SendEmailForm.tsx, src/components/form/textinput/TextInputElement.tsx, src/components/shared.module.scss, src/config/i18n/defaults.json, src/config/i18n/es/resource.json, src/config/i18n/pt-br/resource.json, src/temba/TembaCompletion.module.scss
- Send Email recipent placeholder
- Node asset display
- Disable textarea resize
- Fix Expired string
=> Fix: minor issues

src/temba/TembaCompletion.tsx
- Only check for completion keys events if options are being displayed
=> fix: enter not working on temba completion

WENI-CHANGELOG.md, package.json
2.0.1
----------
* Fix: enter not working on temba completion
* Fix: clear input value if showValue is false
=> release: 2.0.1

src/temba/TembaSelect.tsx
- Fetch next pages from temba-select options
=> fix: temba select get next pages of options

package.json, src/components/button/Button.tsx, src/components/button/__snapshots__/Button.test.tsx.snap, src/components/dialog/__snapshots__/Dialog.test.tsx.snap, src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.tsx.snap, src/components/flow/actions/addurn/__snapshots__/AddURNForm.test.tsx.snap, src/components/flow/actions/localization/__snapshots__/KeyLocalizationForm.test.tsx.snap, src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.tsx.snap, src/components/flow/actions/updatecontact/__snapshots__/UpdateContactForm.test.tsx.snap, src/components/flow/routers/dial/__snapshots__/DialRouterForm.test.tsx.snap, src/components/flow/routers/externalservice/__snapshots__/ExternalServiceRouterForm.test.tsx.snap, src/components/flow/routers/param/__snapshots__/ParamElement.test.tsx.snap, src/components/flow/routers/random/__snapshots__/RandomRouterForm.test.tsx.snap, src/components/flow/routers/result/__snapshots__/ResultRouterForm.test.tsx.snap, src/components/flow/routers/scheme/__snapshots__/SchemeRouterForm.test.tsx.snap, src/components/flow/routers/subflow/__snapshots__/SubflowRouterForm.test.tsx.snap, src/components/flow/routers/ticket/__snapshots__/TicketRouterForm.test.tsx.snap, src/components/flow/routers/wait/__snapshots__/WaitRouterForm.test.tsx.snap, src/components/sidebar/Sidebar.tsx, src/config/i18n/defaults.json, src/config/i18n/es/resource.json, src/config/i18n/pt-br/resource.json, yarn.lock
- ### Updated sidebar tooltip
Related:
- Updated unnnic to 1.16.51
- Updated snapshots related to the unnnic update
- Use buttonNext due to type compatibility
=> Feat: New sidebar tooltips

src/components/flow/routers/case/CaseElement.tsx, src/components/flow/routers/smart/classify/AutomaticClassifyRouterForm.tsx, src/components/flow/routers/smart/response/SmartResponseRouterForm.tsx, src/components/flow/routers/smart/response/__snapshots__/SmartResponseRouterForm.test.ts.snap, src/config/i18n/es/resource.json, src/config/i18n/pt-br/resource.json
- Allow spaces in arguments regex
- Modify smart case element placeholders
=> Fix: Smart cases regex and placeholders

src/components/__snapshots__/index.test.ts.snap, src/components/canvas/Canvas.tsx, src/components/flow/Flow.test.ts, src/components/flow/Flow.tsx, src/components/flow/actions/action/Action.test.ts, src/components/flow/actions/action/Action.tsx, src/components/index.test.ts, src/components/index.tsx, src/components/nodeeditor/NodeEditor.tsx, src/components/revisions/RevisionExplorer.test.ts, src/components/revisions/RevisionExplorer.tsx, src/components/simulator/Simulator.tsx, src/components/sticky/Sticky.tsx
- Removed unused state to props that caused unecessary re-renders
- Modified dragging throttles to give a smoother drag experience
=> Feat: Performance improvements

WENI-CHANGELOG.md, package.json
2.5.2
----------
- Fix: Align updates modal footer text
- Fix: Simulator webhook log height
- Fix: Allow different letters cases in category name
=> release: 2.5.2

src/components/canvas/Canvas.tsx
- When shift is pressed, handle the scroll in the opposite way
=> Feat: Add shift scroll into canvas

src/components/canvas/Canvas.tsx, src/components/sidebar/Sidebar.module.scss, src/components/sidebar/Sidebar.tsx
- Use new material symbols icons in the sidebar and in zoom control
=> Feat: New Sidebar and Zoom Control icons

src/store/thunks.ts
- Check if stickies exists before trying to get the keys
=> fix: sticky parse

public/index.html, src/components/canvas/Canvas.module.scss, src/components/canvas/Canvas.tsx, src/components/canvas/__snapshots__/Canvas.test.tsx.snap, src/components/flow/Flow.tsx, src/components/guidingsteps/GuidingSteps.module.scss, src/components/guidingsteps/GuidingSteps.tsx, src/components/sidebar/Sidebar.tsx, src/components/simulator/Simulator.tsx, src/components/simulator/__snapshots__/Simulator.test.ts.snap, src/config/i18n/es/resource.json, src/config/i18n/pt-br/resource.json, src/flowTypes.ts
- New button to move the canvas into the starting node position
=> [FLOWS-40] - Feat: Find starting node button

package.json, src/components/shared.module.scss
- Update Add Label, URN, Group and Update Contact node colors to blue
- Update open a ticket node color to orange
- Update save a result to pink
- Update available fixed colors with unnnic tokens
=> [FLOWS-271] Feat: Change node colors

WENI-CHANGELOG.md
2.9.0
----------
- Feat: VTEX Product Search
- Feat: Change node colors
- Fix: Width for send_catalog card
=> release: 2.9.0

src/components/flow/routers/case/CaseElement.tsx, src/components/flow/routers/smart/classify/AutomaticClassifyRouterForm.tsx, src/components/flow/routers/smart/response/SmartResponseRouterForm.tsx, src/components/flow/routers/smart/response/__snapshots__/SmartResponseRouterForm.test.ts.snap, src/config/i18n/es/resource.json, src/config/i18n/pt-br/resource.json
- Modify smart and automatic classify phrases text
=> [FLOWS-520] Feat: Smart routers phrases text

src/components/flow/routers/localization/RouterLocalizationForm.tsx, src/components/flow/routers/localization/helpers.ts
- Smart Wait for Response and Automatic Classify now have localization support
=> [FLOWS-582] Feat: add localization support into smart routers

src/components/canvas/Canvas.tsx
- Filter out key inputs that are not directly targeted to the canvas element to avoid incorrect canvas interactions.
=> [FLOWS-623] Fix: Keys affecting canvas on non canvas inputs

src/components/flow/node/helpers.ts
- WeniGPT result was not being listed due to its type was missing in getResultName function condition
=> fix: add wenigpt action to result listing condition

WENI-CHANGELOG.md, package.json
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release version 2.13.1.
Package.json version and Weni Changelog.
=> release: 2.13.1

src/components/canvas/helpers.ts, src/components/flow/actions/updatecontact/UpdateContact.tsx, src/components/flow/routers/menu/MenuRouterForm.tsx, src/components/index.tsx, src/services/FlowStore.ts, src/store/createStore.ts, src/store/mutators.ts, src/utils/debug.ts
* * [ ] Bugfix
* * [X] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Update from CommonJS to ES6 import methods was required
Updated requires to use import structure, lint was also applied
=> refactor: update require to import

WENI-CHANGELOG.md, package.json
* * [ ] Bugfix
* * [x] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Refactor Temba Select code.
Update version on changelog and package.json.
=> chore: bump version

package.json, src/components/flow/actions/whatsapp/sendmsg/SendWhatsAppMsgForm.test.tsx, src/components/flow/actions/whatsapp/sendmsg/SendWhatsAppMsgForm.tsx, src/components/flow/actions/whatsapp/sendmsg/__snapshots__/SendWhatsAppMsg.test.ts.snap, src/components/flow/actions/whatsapp/sendmsg/__snapshots__/SendWhatsAppMsgForm.test.tsx.snap, src/components/flow/actions/whatsapp/sendmsg/helpers.ts, src/flowTypes.ts, src/testUtils/assetCreators.ts
* * [ ] Bugfix
* * [x] Feature
* * [ ] Tests
* * [ ] Other
Add URL button to WhatsApp Card.
Fix cta prop names.
=> [FLOWS-2430] - WhatsApp CTA Button

WENI-CHANGELOG.md
* * [ ] Bugfix
* * [x] Feature
* * [ ] Tests
* * [ ] Other
Add URL button to WhatsApp Card.
Update changelog.
=> [FLOWS-2430] - WhatsApp CTA Button 

src/components/flow/routers/whatsapp/sendproduct/SendWhatsAppProductRouterForm.tsx, src/store/validators.ts
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Allow the use of expressions in the search URL of the native product search card.
Change regex validation.
=> [FLOWS-2621] - Allow the use of expressions in the search URL of the native product search card (@globals)

WENI-CHANGELOG.md, package.json
* * [ ] Bugfix
* * [ ] Tests
* * [X] Other
Update CHANGELOG and package version
=> [FLOWS-2675] Chore: bump floweditor to version 3.0.0

src/components/flow/routers/externalservice/__snapshots__/ExternalServiceRouterForm.test.tsx.snap, src/components/flow/routers/param/__snapshots__/ParamElement.test.tsx.snap, src/components/flow/routers/scheme/__snapshots__/SchemeRouterForm.test.tsx.snap, src/components/flow/routers/whatsapp/sendproduct/__snapshots__/SendWhatsAppProductRouterForm.test.tsx.snap
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> fix: snapshots

WENI-CHANGELOG.md, package.json
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix bugs.
Update changelog.
=> [HT36033] - Release 3.0.1

src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.tsx.snap, src/components/flow/actions/addurn/__snapshots__/AddURNForm.test.tsx.snap, src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.tsx.snap, src/components/flow/actions/updatecontact/__snapshots__/UpdateContactForm.test.tsx.snap, src/components/flow/routers/case/__snapshots__/CaseElement.test.tsx.snap, src/components/flow/routers/caselist/__snapshots__/CaseList.test.tsx.snap, src/components/flow/routers/dial/__snapshots__/DialRouterForm.test.tsx.snap, src/components/flow/routers/externalservice/__snapshots__/ExternalServiceRouterForm.test.tsx.snap, src/components/flow/routers/param/__snapshots__/ParamElement.test.tsx.snap, src/components/flow/routers/random/__snapshots__/RandomRouterForm.test.tsx.snap, src/components/flow/routers/result/__snapshots__/ResultRouterForm.test.tsx.snap, src/components/flow/routers/scheme/__snapshots__/SchemeRouterForm.test.tsx.snap, src/components/flow/routers/subflow/__snapshots__/SubflowRouterForm.test.tsx.snap, src/components/flow/routers/ticket/__snapshots__/TicketRouterForm.test.tsx.snap, src/components/flow/routers/wait/__snapshots__/WaitRouterForm.test.tsx.snap, src/components/flow/routers/whatsapp/sendproduct/__snapshots__/SendWhatsAppProductRouterForm.test.tsx.snap, src/components/form/assetselector/__snapshots__/AssetSelector.test.tsx.snap, src/temba/TembaSelect.tsx
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Enable arrow keys and 'Enter' key when adding new cards.
Check anchorRef render.
=> [FLOWS-2834] - Fix: enable arrow keys and 'Enter' key when adding new cards.

WENI-CHANGELOG.md, package.json
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Enable arrow keys and 'Enter' key when adding new cards.
Bump version.
=> [FLOWS-2834] - Fix: enable arrow keys and 'Enter' key when adding new

WENI-CHANGELOG.md, package.json
* * [ ] Bugfix
* * [x] Feature
* * [ ] Tests
* * [ ] Other
Add text input to brain card.
Updated version.
=> [FLOWS-2830] - Add text input to brain card.

package.json, src/components/flow/actions/callbrain/helpers.tsx
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix text input from barin card.
Fixed the initialize form props.
=> [FLOWS-2830] - Fix:  Add text input to brain card. 

WENI-CHANGELOG.md, package.json
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix text input from barin card.
Updated version.
=> [FLOWS-2830] - Fix: Add text input to brain card.

src/components/canvas/__snapshots__/Canvas.test.tsx.snap, src/components/flow/routers/whatsapp/sendproduct/__snapshots__/SendWhatsAppProductRouterForm.test.tsx.snap
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
Broken snapshots were making the CI to fail
Fixed canvas ans SendWhatsappMessageForm snapshots
=> [FLOWS-2962] Fix: translations tests issue

src/components/flow/routers/smart/classify/AutomaticClassifyRouterForm.test.ts, src/components/flow/routers/smart/classify/__snapshots__/AutomaticClassifyRouterForm.test.ts.snap
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
Improve test coverage
Add AutomaticClassifyRouterForm tests
=> [FLOWS-2883] Test: Add AutomaticClassifyRouterForm tests

src/components/flow/routers/smart/DescriptionAlert/DescriptionAlert.test.ts, src/components/flow/routers/smart/DescriptionAlert/__snapshots__/DescriptionAlert.test.ts.snap
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
Improve test coverage
Added DescriptionAlert tests
=> [FLOWS-2883] Test: Add DescriptionAlert tests

src/components/form/texteditor/TextEditorActions.module.scss, src/components/form/texteditor/TextEditorActions.tsx, src/components/form/texteditor/TextEditorElement.tsx
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Send WhatsApp card emoji.
Add unnnic-emoji-picker.
=> [RS -HT37178] - Fix: send WhatsApp card emoji.

package.json, src/components/flow/actions/whatsapp/sendmsg/SendWhatsAppMsgForm.test.tsx, src/components/flow/actions/whatsapp/sendmsg/SendWhatsAppMsgForm.tsx, src/components/flow/actions/whatsapp/sendmsg/__snapshots__/SendWhatsAppMsgForm.test.tsx.snap, src/components/flow/actions/whatsapp/sendmsg/constants.ts, src/components/flow/actions/whatsapp/sendmsg/helpers.ts, src/components/flow/actions/whatsapp/sendmsg/payments/OrderDetailsSection.module.scss, src/components/flow/actions/whatsapp/sendmsg/payments/OrderDetailsSection.test.tsx, src/components/flow/actions/whatsapp/sendmsg/payments/OrderDetailsSection.tsx, src/components/flow/actions/whatsapp/sendmsg/payments/__snapshots__/OrderDetailsSection.test.tsx.snap, src/components/flow/actions/whatsapp/sendmsg/payments/helpers.ts, src/components/flow/actions/whatsapp/sendmsg/payments/types.ts, src/flowTypes.ts, src/store/nodeEditor.ts
* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
Add support to sending whatsapp order details message
Added new whatsapp order details interaction type
=> Feat: WhatsApp Order Details

src/components/simulator/LogEvent.tsx, src/components/simulator/Simulator.tsx, src/components/simulator/helpers.ts
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The simulator doesn't recognize WhatsApp card messages.
Added whatsApp messages config.
=> [RS-264] - Fix: The simulator doesn't recognize WhatsApp card messages.

src/components/flow/actions/addurn/AddURNForm.test.tsx, src/components/flow/actions/addurn/__snapshots__/AddURNForm.test.tsx.snap
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [CFE-388] test: update addurn tests

src/components/flow/actions/callbrain/CallBrainForm.test.tsx, src/components/flow/actions/callbrain/__snapshots__/CallBrainForm.test.tsx.snap
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [CFE-388] test: update call_brain tests

src/components/flow/actions/addlabels/AddLabel.test.ts, src/components/flow/actions/addlabels/AddLabelsForm.test.ts, src/components/flow/actions/addlabels/AddLabelsForm.test.tsx, src/components/flow/actions/addlabels/__snapshots__/AddLabel.test.ts.snap, src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.ts.snap, src/components/flow/actions/addlabels/__snapshots__/AddLabelsForm.test.tsx.snap
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [CFE-388] test: update addlabels tests

src/components/flow/actions/changegroups/ChangeGroups.test.ts, src/components/flow/actions/changegroups/__snapshots__/ChangeGroups.test.ts.snap, src/components/flow/actions/changegroups/addgroups/AddGroupsForm.test.ts, src/components/flow/actions/changegroups/addgroups/AddGroupsForm.tsx, src/components/flow/actions/changegroups/addgroups/__snapshots__/AddGroupsForm.test.ts.snap, src/components/flow/actions/changegroups/helpers.test.ts, src/components/flow/actions/changegroups/removegroups/RemoveGroupsForm.test.ts, src/components/flow/actions/changegroups/removegroups/__snapshots__/RemoveGroupsForm.test.ts.snap
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [CFE-388] test: update changegroups actions tests

src/components/flow/routers/webhook/WebhookRouterForm.test.tsx, src/components/flow/routers/webhook/__snapshots__/WebhookRouterForm.test.tsx.snap, src/components/flow/routers/webhook/header/HeaderElement.tsx, src/components/flow/routers/webhook/header/__snapshots__/HeaderElement.test.ts.snap, src/testUtils/assetCreators.ts
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [CFE-437] tests: add webhook router tests

src/components/flow/routers/classify/ClassifyRouterForm.test.tsx, src/components/flow/routers/classify/__snapshots__/ClassifyRouterForm.test.tsx.snap, src/vitest-setup.ts
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> [CFE-438] Tests: Add Classify router tests

src/components/flow/actions/localization/WhastsappMsgLocalizationForm.tsx, src/components/flow/actions/localization/WhatsappMsgLocalizationForm.test.tsx, src/components/flow/actions/localization/__snapshots__/WhatsappMsgLocalizationForm.test.tsx.snap, src/components/flow/actions/localization/helpers.ts, src/services/Localization.ts, src/store/helpers.ts, src/testUtils/assetCreators.ts
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
List items could not be translated
Modified localization format for list items titles and descriptions to be handled by goflow
=> [ENGINE-377] Fix: List message localization

package.json, src/components/canvas/Canvas.test.tsx, src/components/canvas/Canvas.tsx, src/components/canvas/__snapshots__/Canvas.test.tsx.snap, yarn.lock
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> Tests: Canvas

WENI-CHANGELOG.md, package.json, src/main.jsx, src/utils/sentry.ts, yarn.lock
* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
=> feat: add sentry integration

src/components/flow/routers/case/CaseElement.test.tsx, src/components/flow/routers/case/__snapshots__/CaseElement.test.tsx.snap
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
=> feat: add CaseElement tests

src/components/simulator/Simulator.tsx
- Updated condition to check for list_message and its list_items before mapping to optionList.
=> fix: improve handling of list messages in Simulator component
